# Generated by Django 4.1.7 on 2023-03-12 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 3, 12, 14, 19, 39, 611345), verbose_name='Опубликована'),
        ),
    ]
